version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-160-120-28.compute-1.amazonaws.com
            database: dfde845tov6oat
            user: vxtjsfasfcaxyv
            password: 3b4594ad0f924a4a49df0f9a8889f5c5f43096567a68432cb34262c458867464
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
